### PR TITLE
WebAmbi HOA as NodeJS

### PR DESCRIPTION
**Pull request by PyrApple**
Dear Archontis,

This pull-request slightly goes against the DOTADIW logic but well, since I had to screw the whole thing up anyway.. here are the main modifications I did there:
- Made the project into a NodeJS: added package.json routines, decomposed FOA and HOA components to to classes, updated the examples accordingly. We may want to address naming after the merge to make 100% sure all make sense and won't ever change again.
- Factorized the examples around a "common.html" file that removes most of examples redundancy.
- Added a readme.mat in ./utils that illustrates the use of Matlab routines to create Ambisonic IRs.
- Manually (and roughly, just to make sure we don't blow ears out there) adjusted example IRs energy.
- Added an HOA_Analyser class

(please don't hate me :)

### CODE REVIEW

**Comment by polarch** [comment]
Heheh,

no hate, that's cool, I like that.. 
I had some doubts about the packaging when I wrote it (everybody can understand how to throw a single .js file in their .html, including people that have never heard of NodeJS), but I like the "proper" way it's looking now. Let's go for it :-).

But you have to give me till Wednesday to have a look to all these changes to understand what's going on, I'll do it during my flight back.

Btw, I noticed that there's a limit to 4th order atm, it wasn't intentional. Not due to the computations but rather due to the WebAudio channelMerger and channelSplitter nodes I'm using - they cannot go for more that 32ch it seems. I think 4th is probably ok for most purposes, if more are needed then each HOA object should initialize multiple splitter/merger nodes.

(Pretty cool this binauralFIR, I had missed it!)

I attach here a list of planned additions from my side, after that I consider it fairly complete for most scenarios, then I'll focus on another web-based ambisonic thingie I started a while ago.
- HOA_reverb (or HOA_diffuser): that's the perceptual ambisonic reverb structure I mentioned before with (N+1)^2 similar but independent RIR tails. This comes from theoretical diffuse field considerations and results in maximum diffuse sensation for the specific order. Mixed with the dry sound it's good for direc-to-diffuse ratio manipulation and externalization/distance control.
- HOA_mirror: that's the trivial mirroring, done by inverting certain HOA components
- HOA_shaping: that's the cool operation of modifying the loudness at different directions, it's complicated on paper but on code it relies on pre-computed factors fixed for each order
- FOA_bandAnalyser: same as the analyser but computes the intensity vector in a few bands, useful for better visualizations
- HOA analyser(2): get the directional power map on a fixed grid of directions, for visualizations

(OPTIONAL)
- FOA/HOA_LSdecoder: decode to loudspeakers based on a user-specified decoding matrix. Problem is, with the limit of WA to 8 outs, I don't seem much reason for it.

Can't think of anything more at the moment. Any other ideas?

Cheers,
Archontis

**Comment by PyrApple** [comment]
Sounds perfect, I would add:
- Consider merging HOA and FOA, with e.g. unified HOA + optional flag for decoder / analyser for Bformat.
- Add support for dynamic HRIR loading based on provided URL as implemented in BinauralFIR (see [HrtfSet.js](https://github.com/Ircam-RnD/binauralFIR/blob/next-master/src/sofa/HrtfSet.js)).

(OPTIONAL) 
- Parametric reverb (while this would take some time to implement, and would be faced with a lot of IP issues on my side, it's nearly a pre-requisite if one wants to use this O-so-cool lib in web game design).

My next project will give me time to test how far we can stretch multi-sources scenarios on standard machines. I may even stumble on architectures requiring decoding-to-loudspeakers features.

Best, 
David

**Comment by polarch** [comment]
Hi David,

just made a local copy of the node version. Does it need any special setting up? I don't do html coding at all (or these jquery stuff, I have no clue about), but linking to the latest jquery version, and trying any of the examples gives me plenty of errors.

I'll check it a bit more, then I may need some guidance..

Archontis

**Comment by PyrApple** [comment]
Dear Archontis, 

It shouldn’t need any setup, a basic http-server on project root (or any http serving tool on ./index.html) does the job here. Now your 

> linking to the latest jquery version

rings a bell, if you can tell me which version and send me the errors log of your browser console. It’s most likely related to the way I factorized the .html element in the ./example/common.html, where the scripts (e.g. foa-player.js) try to access an element of said common.html not yet loaded because of a sluggish jquery.

Do not bother, save your brain for the interesting bit :).

David

**Comment by PyrApple** [comment]
would you care to test if the [rawgit version](https://cdn.rawgit.com/PyrApple/JSAmbisonics/nodejs/index.html) is functional on your side?

**Comment by polarch** [comment]
Rawgit:
- anything with analyser doesn't work (TypeError: analyser is undefined)
- there's a consistent error on all examples for some element (div-reverb?): (TypeError: document.getElementById(...) is null)

**Comment by PyrApple** [comment]
Is the error still there when opened with Chrome?

**Comment by polarch** [comment]
Works on Chrome!

Firefox still gives the errors I mentioned. Interestingly, analyser gets created only for the HOA panner example. 

The (TypeError: document.getElementById(...) is null) persists in all of them.

**Comment by polarch** [comment]
Seems to be this line that causes the second issue in FF:

document.getElementById("div-reverb").outerHTML='';

**Comment by PyrApple** [comment]
It is, that's the jquery thingy I [mentioned earlier](https://github.com/polarch/JSAmbisonics/pull/3#issuecomment-229470722).

That gives us at least common ground for discussion. I'll look over the Firefox issue, here (v47.0.1) it raises no errors (neither analyser nor jquery), yet no sound comes out...

**Comment by PyrApple** [comment]
This [last commit](https://github.com/polarch/JSAmbisonics/pull/3/commits/820d2fd22d739e8f89cb19afef53bed918838316) solved the jquery issue on Firefox on my side (hence clearing all issues mentioned in earlier), if you don't mind checking the [RawGit](https://cdn.rawgit.com/PyrApple/JSAmbisonics/820d2fd22d739e8f89cb19afef53bed918838316/index.html) on yours to confirm.

**Pull request merged**
