### PR TITLE
created classes for 2D Ambisonics

### PR DESCRIPTION
**Pull request by thomasdeppisch**
I added the following classes for the use of 2D (horizontal only) Ambisonics:
monoEncoder2D, orderLimiter2D, sceneRotator2D, sceneMirror2D, binDecoder2D, intensityAnalyser2D, HRIRloader2D_local

2D classes can be used just like the 3D ones. They allow Ambisonics up to 15th order (due to the channel limitations of the Web Audio API). I included an example which is called hoa-panner-sofa2D.html:
https://cdn.rawgit.com/thomasdeppisch/JSAmbisonics/ea73f903/index.html

### CODE REVIEW

**Comment by PyrApple** [comment]
Definitely a worthy addition, though the way it's implemented at the moment it nearly doubles the amount of code with a lot of redundancy. We should try to think of a way to integrate 2D and 3D altogether in a unique set of classes. @polarch, your opinion?

**Comment by polarch** [comment]
I had some communication with Thomas, and even though there is redundancy, it follows nicely the functionality of the library. And 2D processing is practical for many applications (or alternatively, redundancy is less of a problem,than not having 2D functionality). I would go forward to merge the request. We can consider merging the functionality later, e.g. by setting a '2D' or '3D' context for each object or the whole graph..

**Comment by PyrApple** [comment]
agreed

**Comment by thomasdeppisch** [comment]
Thanks for merging. I agree that one nice set of classes with a switchable 2D/3D functionality would be better but I didn't want to mess up your whole code ;)
Before implementing such combined classes we would have needed to agree on the best way to set the 2D/3D flag, context or whatever...

**Pull request merged**
